name: Changesets

on:
  push:
    branches:
      - main

concurrency:
  group: changesets-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - name: Setup pnpm and Node.js
        uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b # v2.1.0
        with:
          version: 12.4.2
          require-lockfile: true
          cache: true
      - name: Create version pull request
        uses: changesets/action@ae32849d5ba541f9ae29e40e22a623bc13562f51 # v2.1.2
        with:
          version-script: pnpm version-packages
          commit-message: "chore: version packages"
          pr-title: "chore: version packages"
          create-github-releases: false
          push-git-tags: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
